# ── Stage 1: Install dependencies ──────────────────────────
FROM node:22-alpine AS deps

WORKDIR /app

# Copy only package files first (cached layer)
COPY package.json package-lock.json ./

# Install all dependencies (need devDeps for the build step)
RUN npm ci

# ── Stage 2: Build the app ─────────────────────────────────
FROM node:22-alpine AS builder

WORKDIR /app

# Copy node_modules from deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy source code
COPY . .

# Every NEXT_PUBLIC_* value is inlined into the bundle at build time, so it must
# be present in THIS stage — a value supplied at `docker run` is ignored. The
# build fails fast if any is missing (see src/lib/org.ts), so a typo surfaces
# here rather than as blank contact details in production.
#
#   docker build --build-arg NEXT_PUBLIC_SITE_URL=https://staging.asspro.fr .
#
# Compose forwards all of these from the .env file (see docker-compose.yml).
ARG NEXT_PUBLIC_SITE_URL=https://asspro.fr
ARG NEXT_PUBLIC_ORG_LEGAL_NAME
ARG NEXT_PUBLIC_ORG_LEGAL_FORM
ARG NEXT_PUBLIC_ORG_SIREN
ARG NEXT_PUBLIC_ORG_DECLARATION
ARG NEXT_PUBLIC_ORG_DIRECTOR
ARG NEXT_PUBLIC_CONTACT_EMAIL
ARG NEXT_PUBLIC_PHONE_MAIN
ARG NEXT_PUBLIC_PHONE_EMERGENCY
ARG NEXT_PUBLIC_ADDRESS_STREET
ARG NEXT_PUBLIC_ADDRESS_POSTAL_CODE
ARG NEXT_PUBLIC_ADDRESS_CITY
ARG NEXT_PUBLIC_ADDRESS_COUNTRY
ARG NEXT_PUBLIC_LINKEDIN_URL
ARG NEXT_PUBLIC_HOST_NAME
ARG NEXT_PUBLIC_HOST_ADDRESS
ARG NEXT_PUBLIC_HOST_PHONE
ARG NEXT_PUBLIC_HOST_URL
ARG NEXT_PUBLIC_MAPS_EMBED_URL

ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL \
    NEXT_PUBLIC_ORG_LEGAL_NAME=$NEXT_PUBLIC_ORG_LEGAL_NAME \
    NEXT_PUBLIC_ORG_LEGAL_FORM=$NEXT_PUBLIC_ORG_LEGAL_FORM \
    NEXT_PUBLIC_ORG_SIREN=$NEXT_PUBLIC_ORG_SIREN \
    NEXT_PUBLIC_ORG_DECLARATION=$NEXT_PUBLIC_ORG_DECLARATION \
    NEXT_PUBLIC_ORG_DIRECTOR=$NEXT_PUBLIC_ORG_DIRECTOR \
    NEXT_PUBLIC_CONTACT_EMAIL=$NEXT_PUBLIC_CONTACT_EMAIL \
    NEXT_PUBLIC_PHONE_MAIN=$NEXT_PUBLIC_PHONE_MAIN \
    NEXT_PUBLIC_PHONE_EMERGENCY=$NEXT_PUBLIC_PHONE_EMERGENCY \
    NEXT_PUBLIC_ADDRESS_STREET=$NEXT_PUBLIC_ADDRESS_STREET \
    NEXT_PUBLIC_ADDRESS_POSTAL_CODE=$NEXT_PUBLIC_ADDRESS_POSTAL_CODE \
    NEXT_PUBLIC_ADDRESS_CITY=$NEXT_PUBLIC_ADDRESS_CITY \
    NEXT_PUBLIC_ADDRESS_COUNTRY=$NEXT_PUBLIC_ADDRESS_COUNTRY \
    NEXT_PUBLIC_LINKEDIN_URL=$NEXT_PUBLIC_LINKEDIN_URL \
    NEXT_PUBLIC_HOST_NAME=$NEXT_PUBLIC_HOST_NAME \
    NEXT_PUBLIC_HOST_ADDRESS=$NEXT_PUBLIC_HOST_ADDRESS \
    NEXT_PUBLIC_HOST_PHONE=$NEXT_PUBLIC_HOST_PHONE \
    NEXT_PUBLIC_HOST_URL=$NEXT_PUBLIC_HOST_URL \
    NEXT_PUBLIC_MAPS_EMBED_URL=$NEXT_PUBLIC_MAPS_EMBED_URL

# Build the Next.js production bundle (standalone output)
ENV NEXT_STANDALONE=true
RUN npm run build

# ── Stage 3: Production image ──────────────────────────────
FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
# Bind the standalone server to all interfaces so it is reachable from outside
# the container (behind the TLS-terminating reverse proxy).
ENV HOSTNAME=0.0.0.0

# Run as an unprivileged user instead of root.
RUN addgroup -g 1001 -S nodejs && adduser -u 1001 -S nextjs -G nodejs

# Copy the public folder
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

# Liveness probe: the lightweight /api/health endpoint must return 200.
# `-O /dev/null` (rather than --spider) is used for maximum BusyBox wget
# compatibility across Alpine versions.
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
  CMD wget --quiet -O /dev/null http://127.0.0.1:3000/api/health || exit 1

# Start using the standalone server generated by Next.js
CMD ["node", "server.js"]
