# ── Stage 1: Install dependencies ──────────────────────────
FROM node:22-alpine AS deps

WORKDIR /app

# Copy only package files first (cached layer)
COPY package.json package-lock.json ./

# Install all dependencies (need devDeps for the build step)
RUN npm ci

# ── Stage 2: Build the app ─────────────────────────────────
FROM node:22-alpine AS builder

WORKDIR /app

# Copy node_modules from deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy source code
COPY . .

# Build the Next.js production bundle
ENV NEXT_STANDALONE=true
RUN npm run build

# ── Stage 3: Production image ──────────────────────────────
FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000

# Copy the public folder
COPY --from=builder /app/public ./public

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000

# Start using the standalone server generated by Next.js
CMD ["node", "server.js"]
